services:


  test_server:
    build:
      context: ./test_server/
    environment:
      URI_SERVER: http://server:8000/
    volumes:
      - ${PWD}/test_server/reports:/pytest/reports:rw
    links:
        - server


  test_client:
    image: cypress/included:10.3.0
    working_dir: /tests
    volumes:
      # USER passthrough
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # mount tests - readonly
      - ${PWD}/test_client/cypress.config.js:/tests/cypress.config.js:ro
      - ${PWD}/test_client/cypress:/tests/cypress:ro
      # mount reports - writeable
      - ${PWD}/test_client/reports:/tests/reports:rw
    entrypoint: ["cypress"]
    command: ["run"]

    links:
        - server
    environment:
      - CYPRESS_BASE_URL=http://server:8000/
